// Package generator handles the creation of standalone lexer source code
// from the constructed DFAs.
package generator

import (
	"bytes"
	"fmt"
	"os"
	"text/template"

	"genanalex/internal/lexer"
)

// LexerData holds all the information necessary to generate a standalone lexer.
type LexerData struct {
	DFAs []lexer.DFAEntry
}

// GenerateSource generates a Go source file for the lexer and writes it to the specified path.
func GenerateSource(outputPath string, entries []lexer.DFAEntry) error {
	tmpl, err := template.New("lexer").Parse(lexerTemplate)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, LexerData{DFAs: entries}); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("writing generated file: %w", err)
	}

	return nil
}

const lexerTemplate = `// Code generated by genanalex. DO NOT EDIT.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

// Token represents a lexical token identified by the generated lexer.
type Token struct {
	Type   string
	Lexeme string
	Line   int
}

// DFA represents a deterministic finite automaton structure.
type DFA struct {
	Transitions map[int]map[rune]int
	Start       int
	Accepting   map[int]bool
	TokenName   string
}

// DFAEntry associates a DFA with a priority for disambiguation.
type DFAEntry struct {
	DFA      DFA
	Priority int
}

var dfas = []DFAEntry{
	{{- range $i, $entry := .DFAs }}
	{
		Priority: {{ $entry.Priority }},
		DFA: DFA{
			Start:     {{ $entry.DFA.Start }},
			TokenName: "{{ $entry.TokenName }}",
			Accepting: map[int]bool{
				{{- range $state, $ok := $entry.DFA.Accepting }}
				{{ $state }}: {{ $ok }},
				{{- end }}
			},
			Transitions: map[int]map[rune]int{
				{{- range $state, $trans := $entry.DFA.Transitions }}
				{{ $state }}: {
					{{- range $char, $next := $trans }}
					{{ printf "%d" $char }}: {{ $next }}, // {{ printf "%q" $char }}
					{{- end }}
				},
				{{- end }}
			},
		},
	},
	{{- end }}
}

func main() {
	srcPath := flag.String("src", "", "path to the source file to tokenize")
	flag.Parse()

	if *srcPath == "" {
		fmt.Fprintln(os.Stderr, "Usage: generated_lexer -src <input_file>")
		os.Exit(1)
	}

	content, err := os.ReadFile(*srcPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading source: %v\n", err)
		os.Exit(1)
	}

	tokens, errors := tokenize(string(content))

	fmt.Println("\n--- Tokens ---")
	for _, tok := range tokens {
		fmt.Printf("[%d] %-12s %s\n", tok.Line, tok.Type, tok.Lexeme)
	}

	if len(errors) > 0 {
		fmt.Println("\n--- Errors ---")
		for _, e := range errors {
			fmt.Println(e)
		}
		os.Exit(1)
	}
}

func tokenize(content string) ([]Token, []string) {
	var tokens []Token
	var errors []string

	runes := []rune(content)
	i := 0
	line := 1

	for i < len(runes) {
		type dfaState struct {
			entry   DFAEntry
			current int
			active  bool
		}

		states := make([]dfaState, len(dfas))
		for k, entry := range dfas {
			states[k] = dfaState{
				entry:   entry,
				current: entry.DFA.Start,
				active:  true,
			}
		}

		lastOKPos := -1
		var lastOKMatches []DFAEntry

		j := i
		for j < len(runes) {
			c := runes[j]
			anyActive := false

			for k := range states {
				if !states[k].active {
					continue
				}
				s := &states[k]
				if nextState, ok := s.entry.DFA.Transitions[s.current][c]; ok {
					s.current = nextState
					anyActive = true
				} else {
					s.active = false
				}
			}

			if !anyActive {
				break
			}

			j++

			var currentAccepting []DFAEntry
			for k := range states {
				if states[k].active && states[k].entry.DFA.Accepting[states[k].current] {
					currentAccepting = append(currentAccepting, states[k].entry)
				}
			}

			if len(currentAccepting) > 0 {
				lastOKPos = j
				lastOKMatches = currentAccepting
			}
		}

		if lastOKPos == -1 {
			errors = append(errors, fmt.Sprintf("line %d: unrecognized character %q", line, runes[i]))
			if runes[i] == '\n' {
				line++
			}
			i++
			continue
		}

		lexeme := string(runes[i:lastOKPos])
		bestMatch := lastOKMatches[0]
		for _, m := range lastOKMatches[1:] {
			if m.Priority < bestMatch.Priority {
				bestMatch = m
			}
		}

		if bestMatch.DFA.TokenName != "skip" {
			tokens = append(tokens, Token{
				Type:   bestMatch.DFA.TokenName,
				Lexeme: lexeme,
				Line:   line,
			})
		}

		for _, r := range lexeme {
			if r == '\n' {
				line++
			}
		}
		i = lastOKPos
	}

	return tokens, errors
}
`
