package generator

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"text/template"

	"genanalex/internal/yapar"
)

type parserTemplateData struct {
	Start       string
	Augmented   string
	IgnoreSet   []string
	Productions []parserProductionData
	ActionRows  []parserActionRowData
	GotoRows    []parserGotoRowData
}

type parserProductionData struct {
	ID   int
	Head string
	Body []parserSymbolData
}

type parserSymbolData struct {
	Name     string
	Terminal bool
}

type parserActionRowData struct {
	State int
	Cells []parserActionCellData
}

type parserActionCellData struct {
	Symbol string
	Action yapar.Action
}

type parserGotoRowData struct {
	State int
	Cells []parserGotoCellData
}

type parserGotoCellData struct {
	Symbol string
	Target int
}

// GenerateParserSource serializa la gramática y la tabla LR en un parser Go autónomo.
func GenerateParserSource(outputPath string, g *yapar.Grammar, table *yapar.ParsingTable) error {
	if g == nil {
		return fmt.Errorf("generating parser source: grammar is required")
	}
	if table == nil {
		return fmt.Errorf("generating parser source: parsing table is required")
	}

	tmpl, err := template.New("parser").Parse(parserTemplate)
	if err != nil {
		return fmt.Errorf("parsing parser template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, buildParserTemplateData(g, table)); err != nil {
		return fmt.Errorf("executing parser template: %w", err)
	}

	if err := os.WriteFile(outputPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("writing generated parser: %w", err)
	}

	return nil
}

func buildParserTemplateData(g *yapar.Grammar, table *yapar.ParsingTable) parserTemplateData {
	data := parserTemplateData{
		Start:     g.Start,
		Augmented: g.Augmented,
	}

	data.IgnoreSet = sortedBoolKeys(g.IgnoreSet)

	data.Productions = make([]parserProductionData, 0, len(g.Productions))
	for _, production := range g.Productions {
		entry := parserProductionData{ID: production.ID, Head: production.Head}
		for _, symbol := range production.Body {
			entry.Body = append(entry.Body, parserSymbolData{Name: symbol.Name, Terminal: symbol.Terminal})
		}
		data.Productions = append(data.Productions, entry)
	}

	data.ActionRows = buildActionRows(table.Action)
	data.GotoRows = buildGotoRows(table.Goto)
	return data
}

func buildActionRows(actionTable map[int]map[string]yapar.Action) []parserActionRowData {
	states := sortedIntKeysFromActions(actionTable)
	rows := make([]parserActionRowData, 0, len(states))
	for _, state := range states {
		row := parserActionRowData{State: state}
		symbols := sortedActionSymbols(actionTable[state])
		for _, symbol := range symbols {
			row.Cells = append(row.Cells, parserActionCellData{Symbol: symbol, Action: actionTable[state][symbol]})
		}
		rows = append(rows, row)
	}
	return rows
}

func buildGotoRows(gotoTable map[int]map[string]int) []parserGotoRowData {
	states := sortedIntKeysFromGotos(gotoTable)
	rows := make([]parserGotoRowData, 0, len(states))
	for _, state := range states {
		row := parserGotoRowData{State: state}
		symbols := sortedStringIntKeys(gotoTable[state])
		for _, symbol := range symbols {
			row.Cells = append(row.Cells, parserGotoCellData{Symbol: symbol, Target: gotoTable[state][symbol]})
		}
		rows = append(rows, row)
	}
	return rows
}

func sortedBoolKeys(values map[string]bool) []string {
	if len(values) == 0 {
		return nil
	}
	keys := make([]string, 0, len(values))
	for key, ok := range values {
		if ok {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)
	return keys
}

func sortedIntKeysFromActions(values map[int]map[string]yapar.Action) []int {
	keys := make([]int, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Ints(keys)
	return keys
}

func sortedIntKeysFromGotos(values map[int]map[string]int) []int {
	keys := make([]int, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Ints(keys)
	return keys
}

func sortedActionSymbols(values map[string]yapar.Action) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedStringIntKeys(values map[string]int) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

const parserTemplate = `// Code generated by yapar. DO NOT EDIT.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

const endMarker = "$"

type Token struct {
	Type   string ` + "`json:\"type\"`" + `
	Lexeme string ` + "`json:\"lexeme\"`" + `
	Line   int    ` + "`json:\"line\"`" + `
}

type Symbol struct {
	Name     string
	Terminal bool
}

type Production struct {
	ID   int
	Head string
	Body []Symbol
}

type ActionKind int

const (
	ActionError ActionKind = iota
	ActionShift
	ActionReduce
	ActionAccept
)

type Action struct {
	Kind         ActionKind
	TargetState  int
	ProductionID int
}

type ParseResult struct {
	Accepted bool
}

type SyntaxError struct {
	Line     int
	GotType  string
	Lexeme   string
	Expected []string
}

func (e *SyntaxError) Error() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.Expected) == 0 {
		return fmt.Sprintf("syntax error at line %d: got %q (%q)", e.Line, e.GotType, e.Lexeme)
	}
	return fmt.Sprintf("syntax error at line %d: got %q (%q), expected %v", e.Line, e.GotType, e.Lexeme, e.Expected)
}

var parserStartSymbol = "{{ .Start }}"
var parserAugmentedStart = "{{ .Augmented }}"

var ignoreSet = map[string]bool{
	{{- range .IgnoreSet }}
	"{{ . }}": true,
	{{- end }}
}

var productions = []Production{
	{{- range .Productions }}
	{
		ID: {{ .ID }},
		Head: "{{ .Head }}",
		Body: []Symbol{
			{{- range .Body }}
			{Name: "{{ .Name }}", Terminal: {{ .Terminal }}},
			{{- end }}
		},
	},
	{{- end }}
}

var actionTable = map[int]map[string]Action{
	{{- range .ActionRows }}
	{{ .State }}: {
		{{- range .Cells }}
		"{{ .Symbol }}": {Kind: {{ .Action.Kind }}, TargetState: {{ .Action.TargetState }}, ProductionID: {{ .Action.ProductionID }}},
		{{- end }}
	},
	{{- end }}
}

var gotoTable = map[int]map[string]int{
	{{- range .GotoRows }}
	{{ .State }}: {
		{{- range .Cells }}
		"{{ .Symbol }}": {{ .Target }},
		{{- end }}
	},
	{{- end }}
}

func main() {
	tokensPath := flag.String("tokens", "", "path to a JSON file containing []Token")
	flag.Parse()

	if *tokensPath == "" {
		fmt.Fprintln(os.Stderr, "Usage: generated_parser -tokens <tokens.json>")
		os.Exit(1)
	}

	tokens, err := loadTokens(*tokensPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading tokens: %v\n", err)
		os.Exit(1)
	}

	result, err := parseTokens(tokens)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Parse error: %v\n", err)
		os.Exit(1)
	}
	if result == nil || !result.Accepted {
		fmt.Fprintln(os.Stderr, "Parse error: input was not accepted")
		os.Exit(1)
	}

	fmt.Printf("[+] Input accepted by parser for %s\n", parserStartSymbol)
}

func loadTokens(path string) ([]Token, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if len(strings.TrimSpace(string(data))) == 0 {
		return nil, nil
	}
	var tokens []Token
	if err := json.Unmarshal(data, &tokens); err != nil {
		return nil, err
	}
	return tokens, nil
}

func parseTokens(tokens []Token) (*ParseResult, error) {
	filtered := filterIgnoredTokens(tokens)
	stream := append([]Token{}, filtered...)
	stream = append(stream, Token{Type: endMarker, Line: endOfInputLine(tokens)})

	stateStack := []int{0}
	index := 0

	for index < len(stream) {
		state := stateStack[len(stateStack)-1]
		lookahead := stream[index]
		action := lookupAction(state, lookahead.Type)

		switch action.Kind {
		case ActionShift:
			stateStack = append(stateStack, action.TargetState)
			index++
		case ActionReduce:
			production, ok := productionByID(action.ProductionID)
			if !ok {
				return &ParseResult{Accepted: false}, fmt.Errorf("unknown production id %d", action.ProductionID)
			}
			if len(stateStack)-1 < len(production.Body) {
				return &ParseResult{Accepted: false}, fmt.Errorf("invalid reduce stack for production %s", describeProduction(action.ProductionID))
			}
			stateStack = stateStack[:len(stateStack)-len(production.Body)]
			gotoState, ok := lookupGoto(stateStack[len(stateStack)-1], production.Head)
			if !ok {
				return &ParseResult{Accepted: false}, fmt.Errorf("missing goto from state %d on %q", stateStack[len(stateStack)-1], production.Head)
			}
			stateStack = append(stateStack, gotoState)
		case ActionAccept:
			return &ParseResult{Accepted: true}, nil
		default:
			return &ParseResult{Accepted: false}, &SyntaxError{
				Line:     syntaxErrorLine(lookahead, tokens),
				GotType:  lookahead.Type,
				Lexeme:   lookahead.Lexeme,
				Expected: expectedTokens(state),
			}
		}
	}

	return &ParseResult{Accepted: false}, &SyntaxError{
		Line:     endOfInputLine(tokens),
		GotType:  endMarker,
		Expected: expectedTokens(stateStack[len(stateStack)-1]),
	}
}

func filterIgnoredTokens(tokens []Token) []Token {
	if len(tokens) == 0 {
		return nil
	}
	filtered := make([]Token, 0, len(tokens))
	for _, token := range tokens {
		if ignoreSet[token.Type] {
			continue
		}
		filtered = append(filtered, token)
	}
	return filtered
}

func lookupAction(state int, symbol string) Action {
	if row := actionTable[state]; row != nil {
		if action, ok := row[symbol]; ok {
			return action
		}
	}
	return Action{Kind: ActionError}
}

func lookupGoto(state int, symbol string) (int, bool) {
	if row := gotoTable[state]; row != nil {
		gotoState, ok := row[symbol]
		return gotoState, ok
	}
	return 0, false
}

func productionByID(id int) (Production, bool) {
	for _, production := range productions {
		if production.ID == id {
			return production, true
		}
	}
	return Production{}, false
}

func describeProduction(id int) string {
	production, ok := productionByID(id)
	if !ok {
		return fmt.Sprintf("production #%d", id)
	}
	if len(production.Body) == 0 {
		return production.Head + " -> ε"
	}
	parts := make([]string, len(production.Body))
	for i, symbol := range production.Body {
		parts[i] = symbol.Name
	}
	return production.Head + " -> " + strings.Join(parts, " ")
}

func expectedTokens(state int) []string {
	row := actionTable[state]
	tokens := make([]string, 0, len(row))
	for symbol, action := range row {
		if action.Kind != ActionError {
			tokens = append(tokens, symbol)
		}
	}
	sort.Strings(tokens)
	return tokens
}

func endOfInputLine(tokens []Token) int {
	for i := len(tokens) - 1; i >= 0; i-- {
		if tokens[i].Line > 0 {
			return tokens[i].Line
		}
	}
	return 1
}

func syntaxErrorLine(lookahead Token, original []Token) int {
	if lookahead.Line > 0 {
		return lookahead.Line
	}
	return endOfInputLine(original)
}
`
